### ISSUE TITLE
Design: Fix size

### ISSUE THREAD

**Issue by gina7484** [swsnu/swpp2020-team6#109]
simpleRoadmap 크기 고정하기 전에 다 같이 결정해줬으면 하는 게 있어서 올립니다!

1)  @khkim610 이 전에 simpleRoadmap 좀 더 날씬하게 해달라고 했던 거 같은데
- margin을 조금 줄여야할 거 같아서 혹시 괜찮은지 (너무 몰려있지는 않을지)
- 줄인다면 어디 부분 크기 줄이면 좋을지
![simple roadmap](https://user-images.githubusercontent.com/46814676/101589179-458ff880-3a2b-11eb-8ccd-e52fc51e00a8.JPG)

2) 로드맵 이미지 비율을 정해야할 것 같은데 얼마로 할지 (4:3 혹은 16:9)
- 이거는 unsplash 같은 사이트에서 로드맵 이미지로 줄 거를 좀 골라보고 어떤 사이즈로 하면 좋을지 정하면 좋을 것 같음
- [unsplash 사이트](https://unsplash.com/)

**Comment by khkim610** [comment]
저는 맨 밑에 like pin comments 이부분을 좀 줄이면 어떨까 싶은데, 다른 정보들에 비해 글씨 크기가 많이 커서..
나머지 부분들은 크기나 간격 다 괜찮은 것 같음

그리고 RoadmapDetail/UserCard.js에서 유저이미지 부분 배경색 유저아이디마다 다르게 하고 또 속에 이니셜 대문자로 되도록 했는데 심플로드맵에도 반영 가능하신가욤

**Comment by gina7484** [comment]
오키! 반영해서 하겠음
