### ISSUE TITLE
url link direction 동작 제대로 안됨

### ISSUE THREAD

**Issue by ddanddan18** [swsnu/swpp2020-team6#114]
## 증상
* 

## 시나리오
로드맵에 있는 url 클릭 시 - link로 안가고 로드맵으로 가는데 웬만하면 no such roadmap이 뜨니까 ... .com 이런거 체크를 추가로해서 link로 보내줘야할 거 같음..

## 스크린샷
![image](https://user-images.githubusercontent.com/35529999/101662855-583b1980-3a8d-11eb-8163-d7d26b48ae0e.png)

**실행환경**
* OS:
* device:

**Comment by gina7484** [comment]
Dealt in PR #130
