### ISSUE TITLE
사인업 기능

### ISSUE THREAD

**Issue by juimdpp** [swsnu/swpp2020-team6#121]
## 증상
사인업 기능에서 password confirm이 가려지지 않습니다.

## 스크린샷

**실행환경**
* OS:
* device:

**Comment by jaewooklee93** [comment]
![image](https://user-images.githubusercontent.com/11328376/101763407-16a87e00-3b22-11eb-9b33-8d070e734827.png)

저는 signup이 되지 않는다고 나옵니다. 혹시 어떤 오류일까요

**Comment by jaewooklee93** [comment]
아이디가 겹치는 문제였군요

**Comment by yg-moon** [comment]
CSS 작업을 하면서 type=password인걸 password-confirm으로 고치면서 발생한 것 같습니다. 바로 수정하겠습니다!

**Comment by jaewooklee93** [comment]
![image](https://user-images.githubusercontent.com/11328376/101763584-4fe0ee00-3b22-11eb-9d3d-2fc2cab77184.png)

링크를 누르면 로드맵이 없다고 나옵니다

**Comment by gina7484** [comment]
@jaewooklee93  링크 주소가 잘못된 것 같습니다.

**Comment by khkim610** [comment]
> ![image](https://user-images.githubusercontent.com/11328376/101763584-4fe0ee00-3b22-11eb-9d3d-2fc2cab77184.png)
> 
> 링크를 누르면 로드맵이 없다고 나옵니다

네, 수업 레포 이슈에서 말씀드렸듯이 url이 http:// 이렇게 시작하는 full url이 아니면 저런 경고가 뜹니다 ㅠㅠ

**Comment by ddanddan18** [comment]
> ![image](https://user-images.githubusercontent.com/11328376/101763584-4fe0ee00-3b22-11eb-9d3d-2fc2cab77184.png)
> 
> 링크를 누르면 로드맵이 없다고 나옵니다

테스팅 시 기타 참고 사항:
로드맵 만들 때 url은 https:// 나 https://가 들어가있는 full url이어야지 정상작동하고 수정 중에 있습니다.

여기에 해당하는 부분입니다! 수정예정에 있습니다

**Comment by gina7484** [comment]
Dealt in #130 , #132
