### ISSUE TITLE
Password Confirm

### ISSUE THREAD

**Issue by ariadne240** [swsnu/swpp2020-team6#122]
## 증상
* Password 는 숨김처리되는데 Confirm 란에서는 숨김처리가 안 됩니다.

## 시나리오
Sign up 할 때 confirm 란에서는 비밀번호 숨김 처리가 안됩니다.

## 스크린샷

**실행환경**
* OS: Mac OS
* device: MacBook

**Comment by yg-moon** [comment]
CSS 작업을 하면서 type=password인걸 password-confirm으로 고치면서 발생한 것 같습니다. 바로 수정하겠습니다!

**Comment by gina7484** [comment]
Dealt in PR #132
