### ISSUE TITLE
도시락 싸는 법 로드맵에 들어갔는데 밑에 더 있는 것이 보이지 않습니다

### ISSUE THREAD

**Issue by sugsugsug** [swsnu/swpp2020-team6#123]
## 증상
* 아래가 안보입니다.

## 시나리오
도시락 싸는 법 로드맵에 들어갔는데 밑에 더 있는 것이 보이지 않습니다

## 스크린샷

![image](https://user-images.githubusercontent.com/52400998/101763960-d4cc0780-3b22-11eb-9d99-42f0500e31d4.png)

**실행환경**
* OS: Window
* device: PC

**Comment by sugsugsug** [comment]
혹시 의도 된거라면 스크롤되게 하는 것도 괜찮을것 같습니다

**Comment by gina7484** [comment]
의도된 것은 아니고 윈도우 크롬에서 하게 되면 브라우저 자체 문제로 간혹 그런 경우가 생기는 것 같습니다. guest mode로 다시 들어오시면 잘 뜰 것 같습니다.
현재 윈도우 크롬 게스트 모드로 들어가니 해당 로드맵이 제대로 뜹니다.

**Comment by gina7484** [comment]
혹은 윈도우 크롬에서 구글계정으로 로그인된 상태에서 로드맵을 작성하게 되면 발생하는 문제 같습니다.
현재 도시락 싸는 법이 여러개 duplicate된 것 같은데 그 중 크롬 브라우저에서 문제가 있는 상황에서 작성하거나 duplicate할 경우 이렇게 보여지기도 합니다.
크롬 브라우저 자체의 문제라 저희도 해결을 못할 것 같아서 이런 문제를 겪으신 분들은
게스트모드로 들어가서 작성하시면 제대로 뜰 것 같습니다.
