### ISSUE TITLE
로드맵 링크들 no such roadmap alert

### ISSUE THREAD

**Issue by magnolia93** [swsnu/swpp2020-team6#124]
## 증상
*로드맵에 들어가서 링크들을 클릭하면 전부 no such roadmap alert가 뜹니다.

## 시나리오
도시락 싸기에서 쿠팡 링크 클릭시
현대미술의 전개에서 비디오나 사이트 클릭시

## 스크린샷

**실행환경**
* OS:
* device:

**Comment by ddanddan18** [comment]
테스팅 시 기타 참고 사항:
로드맵 만들 때 url은 https:// 나 https://가 들어가있는 full url이어야지 정상작동하고 수정 중에 있습니다.

여기에 해당되는 내용입니다! 의견 감사합니다 :)

**Comment by gina7484** [comment]
Dealt in PR #130
