### ISSUE TITLE
[디자인] Landing page alignment

### ISSUE THREAD

**Issue by SPICYJO** [swsnu/swpp2020-team6#125]
## Description

멋진 서비스 감사합니다!

제 피드백은 디자인에 대한 피드백인데요,
저만 그렇게 느끼는지 모르겠지만 Landing page에서 alignment가 어색하게 느껴집니다.
저도 디자인 감각은 부족하지만 어색하다고 느껴지는 부분을 생각해보면 다음과 같습니다.

- "Sign in to create and search for roadmaps." 문구가 center align되어야 할 것 같아요!
- Sign In, Sign Up 버튼이 Username, Password 칸 사이즈에 맞게 되야할 것 같아요!
- 좁은 화면에서는 오른쪽에 있는 로그인 폼이 그림 위를 침범하는데 이를 막아줄 필요가 있을 것 같아요!

**Comment by khkim610** [comment]
좋은 의견 감사드립니다! 디자인은 아직 작업 중이어서 의견 반영하여 마무리해보도록 하겠습니다.

**Comment by yg-moon** [comment]
가상머신 브라우저에서 작업한거랑 결과가 다르게 나와서 말씀하신대로 어색한 부분들이 있습니다. 피드백 감사합니다!
