### ISSUE TITLE
정말 잘 구현하신것같습니다.

### ISSUE THREAD

**Issue by sdm1230** [swsnu/swpp2020-team6#126]
팀2 신동민입니다.
팀6은 정말 ui도 깔끔하고 기능도 잘 됩니다. 배울점이 많은 것 같습니다.
서치했을 때 나오는 페이지의 뷰를 좀 더 다듬으면 더 완벽해질 것 같습니다!

## 증상
* 검색하니 나오는 페이지의 css가 다소 오른쪽에 치우쳐져있는 듯한 느낌이 듭니다.

## 스크린샷
<img width="1440" alt="스크린샷 2020-12-10 오후 8 05 46" src="https://user-images.githubusercontent.com/47305937/101764175-18bf0c80-3b23-11eb-9bc2-63a21f8ff51f.png">

**실행환경**
* OS: macOS
* device: MacBook Pro

**Comment by yg-moon** [comment]
감사합니다 ㅜㅜ
서치도 정렬 상태 고쳐보겠습니다!

**Comment by gina7484** [comment]
감사합니다ㅠㅜ

**Comment by gina7484** [comment]
Dealt in PR #144, #145
