### ISSUE TITLE
로드맵 studying 관련 질문(?)

### ISSUE THREAD

**Issue by latent14** [swsnu/swpp2020-team6#127]
![캡처](https://user-images.githubusercontent.com/62466273/101764353-558b0380-3b23-11eb-9186-0a6d2ab246ef.PNG)

버그라고 말하기는 애매하지만, roadmap의 task들을 다 끝내지 않은채로 finish를 누른 경우에도 finished와 함께 clear버튼만 존재하는데, 의도된 것인가요?

**실행환경**
* OS:
* device:

**Comment by gina7484** [comment]
저희도 모두 채워야지만 finished로 되게끔 할지 고민을 했었는데
그렇게 되면 task가 많을 때 일일히 유저가 가서 클릭을 해야할 것 같아서 현재로서는 이게 더 편할 것 같아서
이렇게 설정을 했습니다.

하지만 말씀해주신 걸 듣고보니, 모든 task를 체크할 수 있는 버튼을 만들고 모두 체크 되어야지만 finish할 수 있게 하는 것도 좋을 것 같습니다. 좋은 지적 감사합니다.

**Comment by gina7484** [comment]
Dealt in PR #142
