### ISSUE TITLE
[eslint] React class 내에서 state initialization error

### ISSUE THREAD

**Issue by khkim610** [swsnu/swpp2020-team6#13]
eslint 적용 후, class 내에서 state initialization 할 때,

> class Article extends Component {
        state = { ...

이런 식으로 작성하면 parse error: unexpected token... 에러가 난다.

해결 step 1:
`yarn add babel-eslint` 후, .eslintrc.js 의 extends와 parseOptions 사이에 `parser: "babel-eslint"` 추가

이러면 이제 새로운 에러가 나온다: State initialization should be in a constructor (react/state-in-constructor)

해결 step 2:
.eslintrc.js 의 rules에 `"react/state-in-constructor": 0, ` 추가

참조:
https://roomedia.tistory.com/entry/이슈-9-Parsing-error-Unexpected-token-eslint
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/state-in-constructor.md

이런 사항 나올때마다 매번 pull request 보내는 게 비효율적일 것 같아서 일단 이슈에 올림

**Comment by gina7484** [comment]
adjusted in #14 and merged.
