### ISSUE TITLE
[Feature] comment: post, edit, delete (frontend)

### ISSUE THREAD

**Issue by gina7484** [swsnu/swpp2020-team6#35]
< frontend >
Bone structure implemented in frontend/containers/RoadmapDetail/RoadmapDetail.js
Please implement (fill in the function body in RoadmapDetail.js)
- [x] commentEditHandler (용균)
- [x] commentDeleteHandler (용균)
- [x] onPostComment (용균)
- [x] testing (진아)

Also, actions and reducers should be implemented.
The reducers should append/edit/delete comment from the roadmapReducer's `selectedUser` state's `comments`.

**Comment by yg-moon** [comment]
이름 변경
- onPostComment
  - commentCreateHandler 로 이름 변경. (handler 끼리 이름 통일)
  - 안에 들어가는 action은 onCreateComment로 해놨음 (design 문서대로)

논의 사항
- design 문서에는 comment Reducer가 따로 있는데 지금은 roadmap reducer에 합친 형태. 둘 중 하나는 수정 필요.
- reducer 작성중, case 문에서 declaration 못하게 하길래 /* eslint-disable no-case-declarations */ 일단 적용시켰음.
