### ISSUE TITLE
[Feature] Pin, Like, Duplicate (+ Post 일부 수정)

### ISSUE THREAD

**Issue by gina7484** [swsnu/swpp2020-team6#45]
## Pin, Like, Duplicate (+ Post 일부 수정)

> 2020-11-13 Pin, Like, Duplicate 관련 Design and Planning 백엔드 스펙 수정 완료 (볼드 표시로 되어있음) 

- [x] 1. POST /api/roadmap/ 수정 필요

  - Roadmap 생성될 때 request.user의 my_roadmaps에 새로운 Roadmap이 추가되어야 함!
    (현재 feature/sprint3-backend-test-roadmap, dev, feature/back-comment 세가지 브랜치 모두 확인한 결과, 해당 기능 빠져있는 것 같음) 

- [x] 2. POST api/roadmap/:roadmap_id/    

  - duplicate 기능 위해서 필요.
  - 자세한 스펙은 [Design and Planning (revisied ver)](https://github.com/swsnu/swpp2020-team6/wiki/2.-Design-and-Planning---revision-draft#backend-api) 참고.

- [x] 3. PUT api/user/like/

  - like 기능
  - 자세한 스펙은 [Design and Planning (revisied ver)](https://github.com/swsnu/swpp2020-team6/wiki/2.-Design-and-Planning---revision-draft#backend-api) 참고.

- [x] 4. PUT api/user/pin/

  - pin기능    
  - 자세한 스펙은 [Design and Planning (revisied ver)](https://github.com/swsnu/swpp2020-team6/wiki/2.-Design-and-Planning---revision-draft#backend-api) 참고.

**Comment by ddanddan18** [comment]
@gina7484 

1. Post roadmap시에 author가 FK이기 때문에 자동으로 추가 됨. Roadmap model의 to_dict() 보면 리버스접근 해서 my roadmap 모으는 거 있음
2. ㅇㅋ
3. 4. 결국은 한 로드맵에 대해서 하는 거니까
`PUT api/roadmap/:id/pin`
이런식으로 하는 게 어떤지?

**Comment by gina7484** [comment]
1,2. 좋아요
3. 찬성! 그럼 design planning 수정하겠음! (like랑 pin 둘다)

**Comment by khkim610** [comment]
지금 POST /api/roadmap/:id (duplicate)하면 response로 empty body가 온다고 되어있는데, front에서 selectedUser의 my_roadmaps를 업데이트해주려면, roadmap simple object가 response로 와야할 것 같습니다. 그리고 POST /api/roadmap/ (create)의 경우에도 마찬가지로 roadmap simple object가 response로 와야할 것 같습니다

**Comment by gina7484** [comment]
나중에 My page 구현에 사용하려면 그렇겠네.
Design and Planning 수정하겠음! (@khkim610 수정되고 연락할테니 확인바람)
@ddanddan18  수정된 Design Planning Duplicate 참고바람!
