### ISSUE TITLE
[Feature] Roadmap description, private

### ISSUE THREAD

**Issue by gina7484** [swsnu/swpp2020-team6#61]
## Description
Add roadmap description, private

## Progress
- Frontend
   - [x] roadmap detail page & testing
   - [x] roadmap edit, create, duplicate page & testing

- [x] Backend

**Comment by khkim610** [comment]
private 기능만 따로 이슈 만들기엔 너무 사소한 것 같아서 합침..
private 기능도 backend에서 구현했는데, detail page에서 private이면 접근 못하게 하는 것 추가해야할 것 같음!

**Comment by gina7484** [comment]
> private 기능만 따로 이슈 만들기엔 너무 사소한 것 같아서 합침..
> private 기능도 backend에서 구현했는데, detail page에서 private이면 접근 못하게 하는 것 추가해야할 것 같음!

detail page에서도 추가했음!
#72
