### ISSUE TITLE
Redux state reset?

### ISSUE THREAD

**Issue by khkim610** [swsnu/swpp2020-team6#70]
페이지가 바뀔 때마다 redux state를 reset하고 다시 server에서 가져오는 작업이 필요하지 않을까?
예를들어, user1이 user2의  mypage에 들어가면 user reducer의 myPageUser가 설정되는데, 그 상태에서 사용자가 logo를 눌러서 home 페이지로 갔다고 하면, user reducer 의 myPageUser는 여전히 똑같은 상태로 남아있을 것임. 그 상태에서 user3의 mypage에 가는 버튼을 눌러서 가면, server에서 user3의 정보가 myPageUser로 오기 전까지 이전 user2의 정보가 myPageUser에 들어있어서, 짧은 시간이겠지만 user2의 정보가 보이는 일이 생길 것 같음.

해결방안:
- 각 container의 componentWillUnmount에서 reset해줌

**Comment by gina7484** [comment]
좋을듯 합니당.
그래서 roadmap Detail에서도 selectedRoadmap을 reset해줌!
근데 나도 그거 goBack전에 해주는게 아니라 willUnmount에서 해줘야겠다.

**Comment by yg-moon** [comment]
모든 container 들은 다 자기 페이지 벗어날때 redux state reset  해주자는 거지? 제일 깔끔하긴 할 듯.

**Comment by yg-moon** [comment]
해당하는 state만 reset 하면 될듯 ㅇㅇ!
