### ISSUE TITLE
ESLint chages

### ISSUE THREAD

**Issue by gina7484** [swsnu/swpp2020-team6#73]
## Description
ESLint에 무시할 rule 추가

- [ ]  eslint-disable-next-line react/jsx-props-no-spreading 
       (material ui에서 이거 안 지키는 문법이 많아서 material ui많이 쓰게 될 것 같으니 지웁시다)
- [ ] 각자 warning 안 뜨게 undefined 들어올 수도 있는 것들은 propstype 선언하는 부분에서 isRequired 지우기

**Comment by khkim610** [comment]
좋아요
