### ISSUE TITLE
비정상적 접근에 대한 redirect 경로 ?

### ISSUE THREAD

**Issue by khkim610** [swsnu/swpp2020-team6#76]
비정상적 접근 (모두 url 입력에 의한 접근)
- sign-in 안 된 상태에서 임의의 페이지 들어가기 (401 또는 각 container render if 문에서 막힘)
- 없는 Roadmap id 입력해서 detail 페이지 접근 (404)
- 없는 user id 입력해서 mypage 접근 (404)
- 타인의 Roadmap edit 페이지 접근 (EditRoadmap render if 문에서 막힘)
- 타인의 private Roadmap detail 페이지에 접근 (RoadmapDetail render if 문에서 막힘)
- ...

`history.back()`, `dispatch(goBack())`을 통한 구현에서 우리가 해결하기 힘든 문제들이 많이 발생하는 것으로 보아, 상기한 비정상적 접근에 대해서 모두 `history.push("/")`, `dispatch(push("/"))`로 처리하는 것이 나아 보임. 우리가 굳이 비정상적 접근에 대해 관대하게(?) 뒤로가기 처리해 줄 필요가 없다고 봄.

정상적 접근에 의한 redirect에서 문제 될 상황은 진아 말마따나 RoadmapDetail -> RoadmapDetail의 경우 말고는 일단 없어보임. 따라서 이 경우에 대해서만 특수하게 처리하는 것이 우리 모두의 정신건강에 더 좋을 것 같습니당

**Comment by yg-moon** [comment]
동의합니다

**Comment by yg-moon** [comment]
데모에서 edge case는 안 다루고 시연만 잘 되면 ok라 하셨으니 더더욱.
