### ISSUE TITLE
Unmount에 대한 state 초기화

### ISSUE THREAD

**Issue by hy00nc** [swsnu/swpp2020-team6#82]
안녕하세요, 아까 질문 주셨던 unmount 시 state가 초기화 하지 않는 상황에 대한 이슈입니다.

일단 새로 mount하면 initialState로 초기화하는 것이 맞으나, 경우에 따라서 Redux 등 사용 이슈로 state가 기존에 것으로 유지 될 수도 있는 것 같습니다. 테스트 코드를 제가 직접 보지 못 해서 확실하진 않습니다.. (파일을 못 찾았네요)

그래서 일단 componentWillUnmount() 를 이용해서 Unmount 전에 redux를 초기화 하는 메소드를 추가하면 해결이 될 것 같습니다.

**Comment by khkim610** [comment]
테스트 코드에서 사용한 state가 redux state가 아니라 component 안에 있는 state였습니다..!
const component = mount(~~~);
~~~~
const instance = component.find(~~~).instance(); 
이렇게 해서 instance.state 확인해보면 이전 test case에서 바뀐 게 남아있네요.
아래 링크가 해당 테스트파일입니다.

https://github.com/swsnu/swpp2020-team6/blob/dev/frontend/src/containers/EditRoadmap/EditRoadmap.test.js

그런데 이전에도 말씀드렸듯이 엄청 크리티컬한 문제는 아니라서 괜찮긴 합니다...
