### ISSUE TITLE
Ubuntu 서버에서 csrf token문제

### ISSUE THREAD

**Issue by ddanddan18** [swsnu/swpp2020-team6#95]
## 증상
* Ubuntu 서버에서 작동시키면 csrf token 문제가 뜸.. 그래서 sign in 도 안된다

## 시나리오
- 서버에서 백/프론트 작동시키고 웹페이지에서 signin하려면 백 터미널에 csrf 403에러가 뜸.. 근데 로컬에서는 잘 됨...

## 스크린샷
![image](https://user-images.githubusercontent.com/35529999/100912246-8fe91500-3513-11eb-92ca-8deda23420b1.png)

**실행환경**
* OS:
* device:

**Comment by hy00nc** [comment]
혹시 settings.py 파일에
ALLOWED_HOSTS = ['localhost', 'YOUR_PUBLIC_DNS_IP']
이거 추가해보셨는데도 안되나요?

**Comment by ddanddan18** [comment]
@hy00nc 네 그거추가해도 안됐었는데 wsgi, nginx 설정하고 나니까 돌아가긴 합니다!
